#!/usr/bin/env python3
"""Generate a tiny self-contained Snakemake workflow for authoring smoke tests."""

from __future__ import annotations

import argparse
import textwrap
from pathlib import Path

SNAKEFILE = r'''
SAMPLES = ["A", "B"]

rule all:
    input:
        expand("results/{sample}.txt", sample=SAMPLES)

rule make_raw:
    output:
        "raw/{sample}.txt"
    shell:
        "mkdir -p raw && printf 'value for {wildcards.sample}\n' > {output:q}"

rule summarize:
    input:
        raw="raw/{sample}.txt"
    output:
        summary="results/{sample}.txt"
    log:
        stderr="logs/summarize/{sample}.err"
    params:
        label=lambda wildcards: f"sample-{wildcards.sample}"
    script:
        "scripts/summarize.py"
'''.lstrip()

SCRIPT = r'''
from pathlib import Path

source = Path(snakemake.input.raw)
target = Path(snakemake.output.summary)
log = Path(snakemake.log.stderr)
target.parent.mkdir(parents=True, exist_ok=True)
log.parent.mkdir(parents=True, exist_ok=True)
text = source.read_text().strip()
target.write_text(f"{snakemake.params.label}: {text}\n")
log.write_text("summarize completed\n")
'''.lstrip()

README = '''
# Minimal Snakemake authoring demo

This workflow is generated by the bundled `minimal_snakefile.py` helper. It is intentionally small and self-contained.

Try:

```bash
snakemake --snakefile Snakefile --cores 1 --dry-run --printshellcmds
snakemake --snakefile Snakefile --cores 1
```

Do not add `--reason` for Snakemake 9.23.1; that legacy flag is invalid.
'''.lstrip()


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        description="Generate a minimal Snakemake workflow with a script directive and named logs.",
    )
    parser.add_argument(
        "--output-dir",
        default="minimal-snakemake-workflow",
        help="Directory to create or update (default: %(default)s).",
    )
    parser.add_argument(
        "--force",
        action="store_true",
        help="Overwrite existing generated files if they already exist.",
    )
    return parser


def write_file(path: Path, content: str, force: bool) -> None:
    if path.exists() and not force:
        raise SystemExit(f"Refusing to overwrite {path}; rerun with --force.")
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content)


def main() -> None:
    args = build_parser().parse_args()
    root = Path(args.output_dir)
    write_file(root / "Snakefile", SNAKEFILE, args.force)
    write_file(root / "scripts" / "summarize.py", SCRIPT, args.force)
    write_file(root / "README.md", README, args.force)
    print(textwrap.dedent(f"""
        Wrote {root}

        Next commands:
          cd {root}
          snakemake --snakefile Snakefile --cores 1 --dry-run --printshellcmds
          snakemake --snakefile Snakefile --cores 1
        """).strip())


if __name__ == "__main__":
    main()
