#!/usr/bin/env python3
"""Print SimpleITK image metadata as JSON for a file or a tiny demo image."""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path
from typing import Any


def _import_simpleitk() -> Any:
    try:
        import SimpleITK as sitk  # type: ignore
    except ImportError as exc:
        raise SystemExit(
            "SimpleITK is not installed. Install the Python package `simpleitk` "
            "and retry, for example: python -m pip install simpleitk"
        ) from exc
    return sitk


def _try_numpy_shape(sitk: Any, image: Any) -> dict[str, Any]:
    try:
        array = sitk.GetArrayViewFromImage(image)
    except ImportError:
        return {"numpy_available": False}
    except Exception as exc:
        return {"numpy_available": None, "array_error": f"{type(exc).__name__}: {exc}"}
    return {
        "numpy_available": True,
        "array_shape": list(array.shape),
        "array_dtype": str(array.dtype),
        "array_writeable": bool(array.flags.writeable),
    }


def _metadata_dict(image: Any) -> dict[str, str]:
    return {key: image.GetMetaData(key) for key in image.GetMetaDataKeys()}


def _physical_probe(image: Any) -> dict[str, Any]:
    origin_index = tuple(0 for _ in range(image.GetDimension()))
    last_index = tuple(size - 1 for size in image.GetSize())
    return {
        "origin_index": list(origin_index),
        "origin_physical_point": list(image.TransformIndexToPhysicalPoint(origin_index)),
        "last_index": list(last_index),
        "last_physical_point": list(image.TransformIndexToPhysicalPoint(last_index)),
    }


def _image_summary(sitk: Any, image: Any, source: str, include_numpy_shape: bool) -> dict[str, Any]:
    summary: dict[str, Any] = {
        "source": source,
        "dimension": image.GetDimension(),
        "size": list(image.GetSize()),
        "origin": list(image.GetOrigin()),
        "spacing": list(image.GetSpacing()),
        "direction": list(image.GetDirection()),
        "pixel_id": int(image.GetPixelIDValue()),
        "pixel_type": image.GetPixelIDTypeAsString(),
        "components_per_pixel": image.GetNumberOfComponentsPerPixel(),
        "metadata": _metadata_dict(image),
        "physical_probe": _physical_probe(image),
    }
    try:
        minimum, maximum = sitk.MinimumMaximum(image)
        summary["minimum"] = minimum
        summary["maximum"] = maximum
    except Exception as exc:
        summary["minimum_maximum_error"] = f"{type(exc).__name__}: {exc}"
    if include_numpy_shape:
        summary.update(_try_numpy_shape(sitk, image))
    return summary


def _demo_image(sitk: Any) -> Any:
    image = sitk.Image([4, 3], sitk.sitkUInt8)
    image.SetSpacing((0.5, 2.0))
    image.SetOrigin((3.0, 14.0))
    image.SetDirection((1.0, 0.0, 0.0, 1.0))
    image.SetMetaData("description", "demo image generated by inspect_image_metadata.py")
    image[1, 2] = 7
    return image


def parse_args(argv: list[str]) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description=(
            "Print JSON metadata for a SimpleITK image file. If --image-file is "
            "omitted, create a deterministic tiny demo image."
        )
    )
    parser.add_argument(
        "--image-file",
        type=Path,
        help="Optional image file readable by SimpleITK.",
    )
    parser.add_argument(
        "--no-numpy-shape",
        action="store_true",
        help="Do not include NumPy array shape/dtype diagnostics.",
    )
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(sys.argv[1:] if argv is None else argv)
    sitk = _import_simpleitk()
    if args.image_file is None:
        image = _demo_image(sitk)
        source = "demo"
    else:
        try:
            image = sitk.ReadImage(str(args.image_file))
        except Exception as exc:
            print(
                json.dumps(
                    {
                        "error": f"{type(exc).__name__}: {exc}",
                        "image_file": str(args.image_file),
                    },
                    indent=2,
                    sort_keys=True,
                ),
                file=sys.stderr,
            )
            return 2
        source = str(args.image_file)
    print(
        json.dumps(
            _image_summary(sitk, image, source, not args.no_numpy_shape),
            indent=2,
            sort_keys=True,
        )
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
