#!/usr/bin/env python3
# Licensed to the Apache Software Foundation (ASF) under one
# or more contributor license agreements.  See the NOTICE file
# distributed with this work for additional information
# regarding copyright ownership.  The ASF licenses this file
# to you under the Apache License, Version 2.0 (the
# "License"); you may not use this file except in compliance
# with the License.  You may obtain a copy of the License at
#
#   http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing,
# software distributed under the License is distributed on an
# "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
# KIND, either express or implied.  See the License for the
# specific language governing permissions and limitations
# under the License.
from __future__ import annotations

import argparse
import ast
import re
import sys
import tomllib
from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:  # pragma: no cover - depends on caller environment
    yaml = None


PROVIDER_MODULE_SECTIONS = (
    "operators",
    "sensors",
    "hooks",
    "triggers",
    "transfers",
)
PROVIDER_CLASS_LIST_SECTIONS = (
    "extra-links",
    "notifiers",
    "secrets-backends",
    "logging",
    "executors",
    "auth-managers",
)
GENERATED_MARKER = "THIS FILE IS AUTOMATICALLY GENERATED"


@dataclass
class CheckResult:
    errors: list[str] = field(default_factory=list)
    warnings: list[str] = field(default_factory=list)

    def error(self, message: str) -> None:
        self.errors.append(message)

    def warning(self, message: str) -> None:
        self.warnings.append(message)

    @property
    def ok(self) -> bool:
        return not self.errors


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Check basic Airflow provider metadata consistency.")
    parser.add_argument(
        "--provider-dir",
        required=True,
        type=Path,
        help="Provider directory containing provider.yaml and pyproject.toml.",
    )
    return parser.parse_args()


def read_text(path: Path, result: CheckResult) -> str | None:
    try:
        return path.read_text(encoding="utf-8")
    except OSError as exc:
        result.error(f"Could not read {path.name}: {exc}")
        return None


def clean_yaml_scalar(value: str) -> str:
    value = value.strip()
    if value in {"|", ">"}:
        return ""
    if len(value) >= 2 and value[0] == value[-1] and value[0] in {"'", '"'}:
        try:
            return ast.literal_eval(value)
        except (SyntaxError, ValueError):
            return value[1:-1]
    return value


def split_yaml_key_value(text: str) -> tuple[str, str] | None:
    if ":" not in text:
        return None
    key, value = text.split(":", 1)
    key = key.strip()
    if not key:
        return None
    return key, clean_yaml_scalar(value)


def parse_provider_yaml_subset(text: str, result: CheckResult) -> dict[str, Any]:
    result.warning("PyYAML is not available; using a conservative provider.yaml subset parser.")
    data: dict[str, Any] = {}
    current_section: str | None = None
    current_item: dict[str, Any] | None = None
    module_list_active = False

    for raw_line in text.splitlines():
        if not raw_line.strip() or raw_line.lstrip().startswith("#") or raw_line.strip() == "---":
            continue
        indent = len(raw_line) - len(raw_line.lstrip(" "))
        stripped = raw_line.strip()

        if indent == 0:
            parsed = split_yaml_key_value(stripped)
            if parsed is None:
                continue
            key, value = parsed
            current_section = key
            current_item = None
            module_list_active = False
            if value:
                data[key] = value
            else:
                data.setdefault(key, [])
            continue

        if current_section in PROVIDER_MODULE_SECTIONS:
            if indent == 2 and stripped.startswith("- "):
                current_item = {}
                data.setdefault(current_section, []).append(current_item)
                module_list_active = False
                parsed = split_yaml_key_value(stripped[2:].strip())
                if parsed:
                    key, value = parsed
                    current_item[key] = value
            elif indent == 4 and stripped == "python-modules:":
                if current_item is not None:
                    current_item.setdefault("python-modules", [])
                module_list_active = True
            elif (
                indent >= 6
                and module_list_active
                and stripped.startswith("- ")
                and current_item is not None
            ):
                current_item.setdefault("python-modules", []).append(clean_yaml_scalar(stripped[2:]))
            continue

        if current_section == "task-decorators":
            if indent == 2 and stripped.startswith("- "):
                current_item = {}
                data.setdefault(current_section, []).append(current_item)
                parsed = split_yaml_key_value(stripped[2:].strip())
                if parsed:
                    key, value = parsed
                    current_item[key] = value
            elif indent == 4 and current_item is not None:
                parsed = split_yaml_key_value(stripped)
                if parsed:
                    key, value = parsed
                    current_item[key] = value
            continue

        if current_section == "connection-types":
            if indent == 2 and stripped.startswith("- "):
                current_item = {}
                data.setdefault(current_section, []).append(current_item)
                parsed = split_yaml_key_value(stripped[2:].strip())
                if parsed:
                    key, value = parsed
                    current_item[key] = value
            elif indent == 4 and current_item is not None:
                parsed = split_yaml_key_value(stripped)
                if parsed:
                    key, value = parsed
                    current_item[key] = value
            continue

        if current_section in PROVIDER_CLASS_LIST_SECTIONS and indent == 2 and stripped.startswith("- "):
            data.setdefault(current_section, []).append(clean_yaml_scalar(stripped[2:]))

    if not data:
        result.error("provider.yaml subset parser did not find any metadata.")
    return data


def load_provider_yaml(path: Path, result: CheckResult) -> dict[str, Any]:
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        result.error(f"Could not read provider.yaml: {exc}")
        return {}
    if yaml is None:
        return parse_provider_yaml_subset(text, result)
    try:
        data = yaml.safe_load(text)
    except yaml.YAMLError as exc:
        result.error(f"Could not parse provider.yaml: {exc}")
        return {}
    if not isinstance(data, dict):
        result.error("provider.yaml must contain a mapping at the top level.")
        return {}
    return data


def load_pyproject(path: Path, result: CheckResult) -> dict[str, Any]:
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as exc:
        result.error(f"Could not parse pyproject.toml: {exc}")
        return {}
    if not isinstance(data, dict):
        result.error("pyproject.toml must contain a mapping at the top level.")
        return {}
    return data


def extract_provider_info_package(text: str, result: CheckResult) -> str | None:
    try:
        tree = ast.parse(text)
    except SyntaxError as exc:
        result.error(f"Could not parse get_provider_info.py: {exc}")
        return None

    for node in ast.walk(tree):
        if isinstance(node, ast.FunctionDef) and node.name == "get_provider_info":
            for statement in node.body:
                if isinstance(statement, ast.Return):
                    try:
                        returned = ast.literal_eval(statement.value)
                    except (ValueError, TypeError):
                        result.warning(
                            "get_provider_info() return is not a literal dict; package check skipped."
                        )
                        return None
                    if not isinstance(returned, dict):
                        result.error("get_provider_info() must return a dictionary.")
                        return None
                    package_name = returned.get("package-name")
                    if isinstance(package_name, str):
                        return package_name
                    result.error(
                        "get_provider_info() return dictionary is missing string key 'package-name'."
                    )
                    return None
    result.error("get_provider_info.py does not define get_provider_info().")
    return None


def get_entry_point_target(pyproject_data: dict[str, Any]) -> str | None:
    project = pyproject_data.get("project")
    if not isinstance(project, dict):
        return None
    entry_points = project.get("entry-points")
    if not isinstance(entry_points, dict):
        return None
    provider_group = entry_points.get("apache_airflow_provider")
    if not isinstance(provider_group, dict):
        return None
    provider_info = provider_group.get("provider_info")
    if isinstance(provider_info, str):
        return provider_info
    return None


def provider_module_root(pyproject_data: dict[str, Any], provider_dir: Path) -> Path | None:
    flit = (
        pyproject_data.get("tool", {}).get("flit", {})
        if isinstance(pyproject_data.get("tool"), dict)
        else {}
    )
    module = flit.get("module", {}) if isinstance(flit, dict) else {}
    module_name = module.get("name") if isinstance(module, dict) else None
    if not isinstance(module_name, str):
        return None
    candidate = provider_dir / "src" / Path(*module_name.split("."))
    return candidate if candidate.exists() else None


def module_path_exists(provider_dir: Path, module_path: str) -> bool:
    relative = Path(*module_path.split("."))
    candidates = [
        provider_dir / "src" / relative.with_suffix(".py"),
        provider_dir / "src" / relative / "__init__.py",
    ]
    return any(candidate.exists() for candidate in candidates)


def class_path_module_exists(provider_dir: Path, class_path: str) -> bool:
    if "." not in class_path:
        return False
    module_path = class_path.rsplit(".", 1)[0]
    return module_path_exists(provider_dir, module_path)


def iter_yaml_module_paths(provider_yaml: dict[str, Any]) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for section in PROVIDER_MODULE_SECTIONS:
        groups = provider_yaml.get(section, [])
        if not isinstance(groups, list):
            continue
        for group in groups:
            if not isinstance(group, dict):
                continue
            for module_path in group.get("python-modules", []) or []:
                if isinstance(module_path, str):
                    found.append((section, module_path))
    for item in provider_yaml.get("task-decorators", []) or []:
        if isinstance(item, dict) and isinstance(item.get("class-name"), str):
            found.append(("task-decorators", item["class-name"].rsplit(".", 1)[0]))
    return found


def iter_yaml_class_paths(provider_yaml: dict[str, Any]) -> list[tuple[str, str]]:
    found: list[tuple[str, str]] = []
    for section in PROVIDER_CLASS_LIST_SECTIONS:
        values = provider_yaml.get(section, [])
        if not isinstance(values, list):
            continue
        for value in values:
            if isinstance(value, str):
                found.append((section, value))
    for item in provider_yaml.get("connection-types", []) or []:
        if isinstance(item, dict) and isinstance(item.get("hook-class-name"), str):
            found.append(("connection-types", item["hook-class-name"]))
    return found


def check_required_files(provider_dir: Path, result: CheckResult) -> tuple[Path, Path, Path | None]:
    provider_yaml = provider_dir / "provider.yaml"
    pyproject = provider_dir / "pyproject.toml"
    get_provider_info_candidates = sorted(provider_dir.glob("src/airflow/providers/**/get_provider_info.py"))
    get_provider_info = get_provider_info_candidates[0] if get_provider_info_candidates else None

    if not provider_yaml.is_file():
        result.error("Missing provider.yaml.")
    if not pyproject.is_file():
        result.error("Missing pyproject.toml.")
    if get_provider_info is None:
        result.error("Missing src/airflow/providers/**/get_provider_info.py.")
    elif len(get_provider_info_candidates) > 1:
        result.warning("Multiple get_provider_info.py files found under provider src tree.")
    return provider_yaml, pyproject, get_provider_info


def check_metadata(provider_dir: Path) -> CheckResult:
    result = CheckResult()
    provider_dir = provider_dir.resolve()
    if not provider_dir.is_dir():
        result.error("--provider-dir must point to a directory.")
        return result

    provider_yaml_path, pyproject_path, get_provider_info_path = check_required_files(provider_dir, result)
    if result.errors:
        return result

    provider_yaml = load_provider_yaml(provider_yaml_path, result)
    pyproject_data = load_pyproject(pyproject_path, result)
    provider_info_text = read_text(get_provider_info_path, result) if get_provider_info_path else None
    if result.errors:
        return result

    provider_package = provider_yaml.get("package-name")
    if not isinstance(provider_package, str) or not provider_package.startswith("apache-airflow-providers-"):
        result.error("provider.yaml key 'package-name' must be an apache-airflow-providers-* string.")

    project = pyproject_data.get("project")
    project_name = project.get("name") if isinstance(project, dict) else None
    if project_name != provider_package:
        result.error(
            f"pyproject.toml project.name {project_name!r} does not match provider.yaml {provider_package!r}."
        )

    if provider_info_text is not None:
        provider_info_package = extract_provider_info_package(provider_info_text, result)
        if provider_info_package and provider_info_package != provider_package:
            result.error(
                "get_provider_info() package-name "
                f"{provider_info_package!r} does not match provider.yaml {provider_package!r}."
            )
        if GENERATED_MARKER not in provider_info_text:
            result.warning("get_provider_info.py does not contain the expected generated-file marker.")

    pyproject_text = read_text(pyproject_path, result)
    if pyproject_text and GENERATED_MARKER not in pyproject_text:
        result.warning("pyproject.toml does not contain the expected generated-file marker.")

    entry_point_target = get_entry_point_target(pyproject_data)
    if not entry_point_target:
        result.error(
            "pyproject.toml is missing [project.entry-points.'apache_airflow_provider'].provider_info."
        )
    elif not entry_point_target.endswith("get_provider_info:get_provider_info"):
        result.error("Provider entry point should target get_provider_info:get_provider_info.")

    for key in ("name", "description", "state", "lifecycle", "integrations"):
        if key not in provider_yaml:
            result.warning(f"provider.yaml is missing common key {key!r}.")

    source_root = provider_module_root(pyproject_data, provider_dir)
    if source_root is None:
        result.warning("Could not locate provider module root from [tool.flit.module].name.")

    for section, module_path in iter_yaml_module_paths(provider_yaml):
        if not module_path_exists(provider_dir, module_path):
            result.warning(f"{section} lists missing module {module_path!r}.")

    for section, class_path in iter_yaml_class_paths(provider_yaml):
        if not class_path_module_exists(provider_dir, class_path):
            result.warning(f"{section} lists class whose module was not found: {class_path!r}.")

    package_slug = re.sub(r"^apache-airflow-providers-", "", provider_package or "")
    if package_slug and entry_point_target and package_slug.replace("-", ".") not in entry_point_target:
        result.warning(
            "Provider entry point target does not appear to contain the provider id from package-name."
        )

    return result


def main() -> int:
    args = parse_args()
    result = check_metadata(args.provider_dir)
    for warning in result.warnings:
        print(f"WARNING: {warning}")
    for error in result.errors:
        print(f"ERROR: {error}", file=sys.stderr)
    if result.ok:
        print("Provider metadata check completed without errors.")
        return 0
    print(f"Provider metadata check failed with {len(result.errors)} error(s).", file=sys.stderr)
    return 1


if __name__ == "__main__":
    sys.exit(main())
